cfg:
  unet_config:
    n_filters_init: 16
    depth: 4
    spatial_dims: 2
    in_channels: 1
    out_channels: 4
    num_res_units: 4
    lr: 0.001
    patience: 5
  binary_target: false
  lr: 0.001
  patience: 5
  threshold: 0.5
  adapt_num_epochs: 10
  cluster_type: centroids
  clue_softmax_t: 0.1
  dataset:
    data_dir: /home/chopra/old/Tasks/data/MNM/
    vendor_assignment:
      train: siemens
      test: ge
    batch_size: 32
    binary_target: false
    non_empty_target: false
  batch_size: 32
  use_uncertainty: true
  kernel_size: 3
  stride: 2
  target_size: 1024
