n_filters_init: 8
depth: 4
spatial_dims: 2
in_channels: 1
out_channels: 4
num_res_units: 4
lr: 1e-3
patience: 5
# infered
# channels: [n_filters_init * 2 ** i for i in range(depth)]
# strides: [2] * (depth - 1)
# binary_target: True if out_channels == 1 else False